version: '3.8'
services:
  ocr_service:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
  face_match_service:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python face_match_service.py
